# Generated by Django 4.2 on 2023-04-13 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sexual_orientation',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non_binary')], default='f', max_length=1),
            preserve_default=False,
        ),
    ]
